### ISSUE TITLE
我设置 "--features", "MS"后,我想要反归一化后的PDF，报错我怎么改 

### ISSUE THREAD

**Issue by zhurong-dot** [lss-1138/SegRNN#21]
>>>>>>>testing : long_term_forecast_ETTh1_96_96_iTransformer_ETTh1_ftMS_sl96_ll48_pl96_dm512_nh8_el2_dl1_df2048_expand2_dc4_fc3_ebtimeF_dtTrue_Exp_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 2785
Traceback (most recent call last):
  File "run.py", line 194, in <module>
    exp.test(setting)
  File "G:\Time-Series-Library-main\Time-Series-Library-main\exp\exp_long_term_forecasting.py", line 207, in test
    outputs = test_data.inverse_transform(outputs.reshape(shape[0] * shape[1], -1)).reshape(shape)
  File "G:\Time-Series-Library-main\Time-Series-Library-main\data_provider\data_loader.py", line 109, in inverse_transform
    return self.scaler.inverse_transform(data)
  File "F:\shuoAPP\anaconda\envs\QHZS\lib\site-packages\sklearn\preprocessing\_data.py", line 1052, in inverse_transform
    X *= self.scale_
ValueError: operands could not be broadcast together with shapes (3072,49) (7,) (3072,49)

**Comment by lss-1138** [comment]
看起来用的是Time-Series-Library的代码，建议问下Time-Series-Library的实现
