### ISSUE TITLE
mismatch of tensor sizes in the addition operation

### ISSUE THREAD

**Issue by m6129** [lss-1138/SegRNN#5]
Hello.
mismatch of tensor sizes in the addition operation [in kaggle](https://www.kaggle.com/code/mrantonzaitsev/segrnn-official/notebook)
What do I need to do to get rid of the problem?
```
Traceback (most recent call last):
  File "/kaggle/working/SegRNN/run_longExp.py", line 141, in <module>
    exp.train(setting)
  File "/kaggle/working/SegRNN/exp/exp_main.py", line 168, in train
    outputs = self.model(batch_x)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/kaggle/working/SegRNN/models/SegRNN.py", line 133, in forward
    y = y.permute(0, 2, 1) + seq_last
RuntimeError: The size of tensor a (0) must match the size of tensor b (256) at non-singleton dimension 0
^C
Traceback (most recent call last):
  File "/kaggle/working/SegRNN/run_longExp.py", line 141, in <module>
    exp.train(setting)
  File "/kaggle/working/SegRNN/exp/exp_main.py", line 140, in train
    batch_x = batch_x.float().to(self.device)
KeyboardInterrupt
```

**Comment by lss-1138** [comment]
I've reviewed your [modified code](https://github.com/m6129/SegRNN). I noticed that you're attempting a prediction with a horizon of 24, but the seg_len is still set to 48. It's important to note that seg_len should be set to the common factor of seq_len and horizon to ensure both input and output sequences can be properly segmented.

**To address this, you can directly modify seg_len to 24 and see if it resolves the issue.** Additionally, seg_len is a crucial hyperparameter that can affect the model's performance, so in practical applications, be sure to fine-tune this parameter carefully.

**Comment by m6129** [comment]
Thank you very much for the quick response.
It helped me
